### PR TITLE
Project Capstone: Air Pollution APP

### PR DESCRIPTION
**Pull request by danifromecuador**
## In this pull request I've:
- Created a `dev` branch and settled it as the main branch to follow the git flow pattern
- Created a `setup` branch
- Created a [React](https://react.dev/learn) App  using [Vite](https://vitejs.dev/guide/) `npm create vite@latest`
- Installed [Microverse](https://www.microverse.org/) [linters for react and redux](https://github.com/microverseinc/linters-config/tree/master/react-redux)
- Installed React libraries, dependencies, and utilities:
  - `npm install react-redux`
  - `npm install @reduxjs/toolkit`
  - `npm install redux-thunk`
  - `npm install --save-dev redux-devtools-extension`
- Created basic folders and files structure for a React-Redux App
- Created components and navigation between `Home.jsx` and `Details.jsx` pages
- Created a hardcoded array
- Rendered `Home.jsx` and `Details.jsx` pages using the hardcoded array
- Created the store
- Created a reducer to log a sample data from a fetched API
- Created a hardcoded array with the 100 main cities of the world
- Used the [geocoding API](https://openweathermap.org/api/geocoding-api) to obtain the latitude and longitude of a given city name
- Used the [air pollution API](https://openweathermap.org/api/air-pollution) to obtain data based in the lat and long and the name of the city for each city of the array
- Stored in the store the filtered data for each city
- Change the address when the user clicks on a city
- Render `Details.jsx` page when the user clicks on a city
- The `Details.jsx` page should render data based on it's address bar direction
- Filter cities by search
- Style all the components using these [design lines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs))
- Test the project using react testing library
- Deploy the project using Netlify
- Recorded a [video](https://www.loom.com/share/a89e11d7008b4cc3a88437dadb4fa0f8) presentation
- Final overview: 
image

### CODE REVIEW

**Review by 1GORDON — CHANGES_REQUESTED** [review]
##
## Hi @danifromecuador ✋

Good job so far!

## Highlights!
- Nice video presentation✔️ 
- App runs as expected ✔️
- All tests are passing ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] As stated in the project requirements, kindly ensure your README contains an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).
- [ ] Kindly remove all linter disabling lines of code from your entire project. Linter checks help us write more professional code.
- [ ] Kindly remove all commented code from your entire project as this is regarded as a bad practice.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@c1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by topeogunleye — CHANGES_REQUESTED** [review]
Hi @danifromecuador, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

Try-Again

## Highlights 🍾 
- Removed commented-out code. ✔️ 
- Added Acknowledgements to Behance/Dribble designer. ✔️ 

## Suggested changes
- I'm writing it here because I couldn't use inline comments
- As suggested by the previous reviewer, please kindly remove all disabling lines of code from your entire project. Linter checks help us write more professional code.
1. /workspace/metrics-app/src/components/Input.jsx
image

2. /workspace/metrics-app/src/components/Input.jsx

imageCheers and Happy coding!

3. /workspace/metrics-app/src/components/Items.jsx
image

4. /workspace/metrics-app/src/pages/Details.jsx
image

5. /workspace/metrics-app/src/pages/Home.jsx
image


👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by danifromecuador** [comment]
Dear reviewers, I need React for testing, if I delete the import React line, tests will not work, if I just let the React Line the linters will give an error about unused variables because I am using vite, what should I do?

**Comment by topeogunleye** [comment]
> Dear reviewers, I need React for testing, if I delete the import React line, tests will not work, if I just let the React Line the linters will give an error about unused variables because I am using vite, what should I do?

@danifromecuador. I guess that's a reasonable use of import React line, please put it back.

**Review by topeogunleye — APPROVED** [review]
Hi @danifromecuador, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

> ## (Highlights) Good Points: 💪 
> Removed ESlint disablers. ✔️ 

çrpik-kurdî-impressive



Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear
Please, remember to tag @topeogunleye in your question so I can receive the notification.
 
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
